language: python
python:
 - "2.7"


before_install:
  - git submodule update --init --recursive

install: 
 - pip install -r requirements.txt --use-mirrors --target=libs
 - pip install -r requirements_dev.txt --use-mirrors

script:
 - python run_tests.py