application: volcanicpixels
version: new

module: web

runtime: python27
threadsafe: yes
api_version: 1

handlers:
 - url: /assets
   static_dir: assets

 - url: .*
   script: volcanicpixels.frontend.app

builtins:
 - deferred: on