application: volcanic-pixels
version: live

module: default

runtime: python27
threadsafe: yes
api_version: 1

handlers:
- url: /assets
  static_dir: assets

- url: .*
  login: admin
  script: volcanicpixels.frontend.app

builtins:
- deferred: on

libraries:
- name: pycrypto
  version: "2.6"

skip_files:
- node_modules(.*)
- node_modules
- node_modules/
