application: volcanic-pixels
version: live

module: default

runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /assets
  static_dir: assets

- url: /api/1/.*
  script: volcanicpixels.legacy.app


- url: /ssl.*
  script: volcanicpixels.frontend.app
  secure: always

- url: .*
  script: volcanicpixels.frontend.app
  secure: optional

inbound_services:
- warmup

builtins:
- deferred: on

libraries:
- name: pycrypto
  version: "2.6"
- name: ssl
  version: latest

skip_files:
- node_modules(.*)
- node_modules
- node_modules/
